### ISSUE TITLE
Skipping JaCoCo execution due to missing execution data file:C:

### ISSUE THREAD

**Issue by timk-blip** [timk-blip/lecture_7_1#1]
**Шаги воспроизведения**:
Шаг 1. Скачать по ссылки  [репозиторий](https://github.com/timk-blip/lecture_7_1); 
Шаг 2. Запустить скаченый проект в приложении в IntelliJ IDEA MAVEN
Шаг 3. Запустить фазу verify
**Ожидаемый результат** - тест должен не пройти, JaCoCo активен.
**Фактический результат** - Skipping JaCoCo execution due to missing execution data file:C:
так же не создается папка site
смотрите картинку ниже
![image](https://user-images.githubusercontent.com/65917995/87337551-4855f280-c54c-11ea-9caa-ecab80120955.png)
![image](https://user-images.githubusercontent.com/65917995/87337702-8a7f3400-c54c-11ea-82ac-264e242eb01c.png)

**Окружение** - Windows 10, Java11.0.7_1

**Comment by andrew-pahomov** [comment]
Проблема с запуском Jacoco возникает вследствие наличие в полном пути папки с проектом русских слов. То есть надо переименовать папку `учеба` и назвать её словом на латинице, например `study`.

**Comment by timk-blip** [comment]
@andrew-pahomov благодарю за помощь!)
